### ISSUE TITLE
AccessViolationException when calling C# functions

### ISSUE THREAD

**Issue by Xaroth** [jsimmons/LuaSharp#2]
I pushed a function on the stack using this:

lua["debug"] = new CallbackFunction(lua_Debug);

with lua_Debug as follows:

```
    internal static int lua_Debug(IntPtr state)
    {
        int args = 0;
        int stack = LuaLib.lua_gettop(state);
        if (stack == 2)
        {
            string format = LuaLib.lua_tostring(state, 1);
            string arg = LuaLib.lua_tostring(state, 2);
            Console.WriteLine(format, arg);
        }
        return args;
    }
```

Now when running the following lua code:
debug("TEST: {0}", "TEST")

I see that indeed, "TEST: TEST" appears on the console, as expected.. however, after returning the debugger kicks in to this section of LuaLib.cs:

```
    public static bool luaL_dofile( IntPtr state, string filename )
    {
        return ( luaL_loadfile( state, filename ) == LuaEnum.Ok ) && ( lua_pcall( state, 0, (int)LuaEnum.MultiRet, 0 ) == LuaEnum.Ok );
    }
```

with an AccessViolationException

using Lua51.dll versioned 5.1.4.0, and the last git export of LuaSharp and LuaWrap

any clues?

**Comment by exectails** [comment]
Any solution to this yet? I've tried the proposed solution, but that didn't actually change anything.

**Comment by jsimmons** [comment]
Uh the delegate is probably being garbage collected because it's not pinned on the .NET side.

Try storing it somewhere accessible in your code to check whether this is the case.

**Comment by exectails** [comment]
Actually, what solved the problem was adding `[UnmanagedFunctionPointer(System.Runtime.InteropServices.CallingConvention.Cdecl‌​)]` to the delegate definition.

**Comment by jsimmons** [comment]
Ah of course that also makes sense!

You will have to pin the delegate on the .NET side though so it doesn't get collected. Not sure whether any .NET runtimes will actually collect the delegate but better safe than sorry.

Anyway I'll add that now.
